[project]
name = "ds-salaries-predict"
version = "0.1.0"
description = "Predicting Salaries of Data Scientists"
authors = [{ name = "Promchai Chooseang" }, { name = "Pannatorn Sriwongpan" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
]

[dependency-groups]
dev = [
    "ruff>=0.11.10",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"] # Add import sorting
